### ISSUE TITLE
Compatibility with moonbeam launch

### ISSUE THREAD

**Issue by joelamouche** [PureStake/moonbeam-truffle-box#2]
I want my box to connect to a `launch` instance of moonbeam: `Starting a Collator for parachain 1000: 5Ec4AhPZk8STuex8Wsi9TwDtJQxKqzPJRCH7348Xtcs9vZLJ, Collator port : 34100 wsPort : 34102`

If I try to connect to `http://localhost:34100/` I get `Error: read ECONNRESET`
If I get the ws: `const webSocketProvider = new Web3.providers.WebsocketProvider("ws://localhost:34102/");` I get `Error: Invalid request`

All of this wile trying to run `truffle migrate --network dev`

**Comment by joelamouche** [comment]
@crystalin is it possible that moonbeam launch doesnt open ports for http?

**Comment by tgmichel** [comment]
> is it possible that moonbeam launch doesnt open ports for http?

Yeah, I have the same problem, and ended up adding `--rpc-port` manually to `launch`.

**Comment by joelamouche** [comment]
thanks @tgmichel 
And then you just specify a random port?

**Comment by tgmichel** [comment]
> And then you just specify a random port?

I don't know why it didn't pick up, but as a shortcut I just followed the pattern described there and assigned manually:

- Collator `alice` with `--rpc-port=34101`.
- Collator `bob` with `--rpc-port=34111`.

**Comment by joelamouche** [comment]
So where do you add the `--rpc-port=34101` flag? also as you said it should be made available according to the readme
