### ISSUE TITLE
This version of µWS is not compatible with your Node.js build

### ISSUE THREAD

**Issue by ltfschoen** [PureStake/moonbeam-truffle-box#7]
if i follow these installation instructions https://docs.moonbeam.network/builders/build/eth-api/dev-env/truffle/
and use the latest version of Node.js that works v19.9.0 (see https://github.com/npm/cli/issues/6532#issuecomment-1597885794)
then after installing truffle i get the following error:

```
root@ink:/app# truffle run moonbeam --help
This version of µWS is not compatible with your Node.js build:

Error: Cannot find module '../binaries/uws_linux_x64_111.node'
Require stack:
- /usr/lib/node_modules/truffle/node_modules/ganache/node_modules/@trufflesuite/uws-js-unofficial/src/uws.js
- /usr/lib/node_modules/truffle/node_modules/ganache/dist/node/core.js
- /usr/lib/node_modules/truffle/build/help.bundled.js
- /usr/lib/node_modules/truffle/node_modules/original-require/index.js
- /usr/lib/node_modules/truffle/build/cli.bundled.js
Falling back to a NodeJS implementation; performance may be degraded.


"truffle run moonbeam --help" is an invalid command
Truffle v5.10.0 (core: 5.10.0)
Node v19.9.0
```

I think the documentation should specify what version of Node.js and NPM are supported.
I also think this template could be updated to include the engines node and npm properties as mentioned here https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines so users know what versions to install 

At the moment, the README also just mentions the following, but I think this could be removed if we instead just suggest to the user to switch to the latest LTS version 18.x
```
_Note:_ We noticed that if you are using `npm v7.0.15` you might have some errors when running `npm install`. To fix this you can downgrade npm to an older release such as `6.14.9` or `7.0.8` by running, for exmaple, `npm install -g npm@v6.14.9`.
```

**Comment by ltfschoen** [comment]
I ended up resolving that error by installing the LTS version of Node.js (i.e. 18.x)

* Install Node.js v18.x (i.e. v18.16.0) since has LTS https://nodejs.org/en/download/releases
* Use an LTS version of NPM to avoid error `This version of µWS is not compatible with your Node.js build` https://stackoverflow.com/questions/71081725/this-version-of-%C2%B5ws-is-not-compatible-with-your-node-js-build-error-node-loade

```bash
apt-get remove -y nodejs
rm -rf /usr/lib/node_modules/
curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
apt-get install -y nodejs
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list
apt-get update && apt-get install yarn
npm config rm proxy
npm config rm https-proxy
npm install -g truffle
chmod 755 /usr/lib/node_modules/truffle/build/cli.bundled.js
truffle --version
```

**Comment by crystalin** [comment]
Thank you @ltfschoen for the feedback.
@albertov19 maybe something to add in the documentation.

**Comment by albertov19** [comment]
@eshaben :)

**Comment by eshaben** [comment]
Added documentation to the readme (pending in PR #12). Thanks!
